### ISSUE TITLE
porting to esp32

### ISSUE THREAD

**Issue by HNeumeier** [stanekTM/RX_Cabell_8ch_Motor_Servo#1]
Hello Stanek,
you have done a very good Job, is it possible to change the code to be running on a esp32, the Servo Channels are not needed only the 2x motor controller.
thanks.

**Comment by stanekTM** [comment]
Hi @HNeumeier,
Thanks, the code was primarily modified for "small" processors, miniature rc models.
Unfortunately I don't have an ESP32, but porting would definitely be possible, I think controlling the PWM motors would be in a larger frequency range.

**Comment by HNeumeier** [comment]
Hi Stanek,
for me it is not possible to convert the Cabell Protocol to the esp because of thuch many hardware specific statements, i will use your protocoll, that's easy to convert to different plattforms, Thanks.

**Comment by stanekTM** [comment]
Hi @HNeumeier,
I'm sorry, I'm stuck with AVR processors for now, my future interest will be LGT processors. Feel free to share your progress, I'll be following your github.
